name: Docker Image CI

on:
  push:
    tags:        
      - '*' 
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Use tag
      run: echo ${{ steps.meta.outputs.tags }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag asp-net-docker:${{ steps.meta.outputs.tags }}
